### ISSUE TITLE
Publish it to the main docker registry?

### ISSUE THREAD

**Issue by stardust85** [Klowner/docker-gitlab-mirrors#2]
Hi,

I noticed that most projects put their container images to the cetral docker registry so in docker-compose.yml you put something like

```
gitlabmirror:
   image: klowner/gitlab-mirrors:latest
```

instead of:

```
gitlabmirror:
  image: quay.io/klowner/gitlab-mirrors:latest
```

I'm relatively new to docker, so maybe this request doesn't make sense...

**Comment by Klowner** [comment]
I could publish the container in docker hub as well, but I prefer quay.io
since they provide automated container builds.

Is there a reason that you need it published on the official registry or is
it just a matter of preference?

**Comment by stardust85** [comment]
It was more a question than a bug report to find out what is the difference between these two ways. You can close it :)

**Comment by Klowner** [comment]
Oh, no worries. They're largely the same, they're both docker registry servers. The official registry has no bells or whistles like some of the others such as quay.io.

You can tag a container with just about any string, but if you use the `hostname/namespace/name` pattern then you can `docker push` and `docker pull` to the corresponding registry. For example, if you decided to run your own registry at `docker.example.com` you would tag your images with `docker.example.com/startdust85/docker-gitlab-mirrors:latest` and then when you `docker push` that it'll go to that registry server.

Quay.io is cool because you can set it up so if you push to a Github repository, Quay will start an automated build of the `Dockerfile` in your repository and then serve the resulting image.
